version: 1
accounts:
- name: validator
  coins:
    - 200000000stake
- name: faucet
  coins:
    - 200000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: faucet
  coins:
    - 100000stake

validators:
- name: validator
  bonded: 200000000stake
