version: 1
accounts:
- name: validator
  coins:
    - 200000000stake
- name: faucet
  coins:
    - 2000000000000uopen
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: faucet
  coins:
    - 100000uopen

validators:
- name: validator
  bonded: 200000000stake

build:
  main: cmd/sourcehubd
